dist: xenial
sudo: required

language: python
python:
    - 3.5
    - 3.6

install:
    - sudo apt-get install libmpv1 -y --force-yes
    - pip install codecov
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt

script:
    - make pytest

after_success:
  - codecov
