dist: xenial
sudo: required
services:
    - docker

language: python
python:
    - 3.5
    - 3.6

install:
    - sudo apt-get install libmpv1
    - pip install -r dev-requirements.txt

script:
    - make pytest
